apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
       containers:
        - name: consumer
          image: docker.io/bitnami/kafka:3.2.3-debian-11-r1
          command:
          - /bin/sh 
          - -c
          - "kafka-console-consumer.sh --bootstrap-server kafka.default.svc.cluster.local:9092 --topic test --from-beginning"

